language: rust

rust:
  - stable
  - nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssl

matrix:
  allow_failures:
    - script:
        - cargo install clippy --verbose --force
        - cargo clippy -- -D clippy
  include:
  - rust: "nightly"
    script:
      - cargo install clippy --verbose --force
      - cargo clippy -- -D clippy
